### PR TITLE
Added domains from cock.li

### PR DESCRIPTION
**Pull request by makitsune**
https://cock.li/register

By the way, when I have free time I would like to write a script for adding new entries to list.txt where you can merge two lists or individual domains together, and it will do something along the lines of the Unix command `sort -u list.txt` (-u for unique). It would make life so much easier.

Also, thank you for making this. I'm using the node module in production already!

### CODE REVIEW

**Comment by FGRibreau** [comment]
> By the way, when I have free time I would like to write a script for adding new entries to list.txt where you can merge two lists or individual domains together, and it will do something along the lines of the Unix command sort -u list.txt (-u for unique). It would make life so much easier.

that would be perfect, please open a PR to start it as a github actions :)

**Comment by notpushkin** [comment]
Please reconsider this :( There is a lot of legitimate users of this provider (including myself).

**Comment by makitsune** [comment]
I know plenty of people from the cockli mailing list that all use their service but repetitively making accounts is really easy there and there's no personal verification and making it hard to make more like Google. Email addresses are a terrifying monopoly and it's sad and it sucks. I have a terrible gmail address but I don't have any choice to change it because Google won't let me but at least it will never get rejected when signing up on websites

I've used cockli in the past and apart from the horrifying domain names they own, I've had problems with it being rejected when making accounts.

**Comment by notpushkin** [comment]
@makitsune But I mean, it's not a reason to make it even worse – many people use domain lists like this one to restrict making accounts. I'm (lazily) fighting this tendency now: repetitive accounts may be a problem for some sites, but I don't think blocking legit email providers is a right solution, even if getting a mailbox there is reeeeeaaally easy.

And the most of their domain names are direful, I agree. I personally use only `@airmail.cc` and `@firemail.cc` (and `@420blaze.it` for the mailing list).

**Comment by makitsune** [comment]
@notpushkin I really wish I knew the right thing to say because I agree with you :(

Hopefully one day passwords, accounts and email standards will change. Google is dominating email and it makes me sad. The only reason I added those domains here is because I'm having spam problems with cockli and I use mailchecker in production for a social vr game that's causing harassment to users.

I wonder if perhaps the list could be split into two where you have domains that generate email addresses literally made to be thrown away, and domains where you have to sign up but have no limit. Then the developer gets a choice between which lists to use.

**Comment by notpushkin** [comment]
@makitsune Perhaps splitting the list would be the best option here! I guess we can have a few actually:

- **whitelist** – email providers that require second factor (e. g. mobile phone, like Google) to signup
- _(other domains go between these two by default)_
- **graylist** – email providers with easy signup
- **blacklist** – throwaway / temporary mailboxes

Then it would be up to developer how to use these (for example, blacklisted domains aren't allowed at all and graylisted get to SMS verification or manual approval or maybe just higher moderator attention etc). What do you think?

**Comment by FGRibreau** [comment]
Segmented list seems indeed a good idea :+1:

**Comment by FGRibreau** [comment]
Segmented list (`graylist` + `blacklist`) seems indeed a good idea :+1:, Mailchecker default behavior should still be `graylist`+`blacklist` though.
I don't think we need a `whitelist`.

**Pull request merged**
