### PR TITLE
Remove fastmail.fm provider as it is legitimate

### PR DESCRIPTION
**Pull request by kennym**
We have active users with our product with that email provider, and they're legitimate users. Also fastmail.fm doesn't offer you to create disposable emails.

### CODE REVIEW

**Comment by FGRibreau** [comment]
Fixed in v1.5.1 :)

**Comment by kennym** [comment]
@FGRibreau thanks!

I would be cool if you could cherry-pick the changes next time so I would appear in "Contributors" section. :smile: No big deal.

**Comment by FGRibreau** [comment]
@kennym indeed, I'm sorry! I intentionally did my own PR to remove fastmail.fm in order to be sure that no other domain were removed, what line should I add inside the "contributor" section in package.json?

**Comment by kennym** [comment]
I am referring to this section: https://github.com/FGRibreau/mailchecker/graphs/contributors

**Comment by FGRibreau** [comment]
Oh I see, I'm sorry, I won't be able to do this soon but if you find any other issue related to mailchecker, be sure I will merge it instantanely! I'm really sorry for the inconvenience :(

**Comment by kennym** [comment]
@FGRibreau no inconvenience at all! :smile:

**Pull request closed without merging**
