### PR TITLE
Remove "139.com" from list.txt.

### PR DESCRIPTION
**Pull request by Yuki1536**
This is a free email service which runs by China Mobile.

### CODE REVIEW

**Comment by FGRibreau** [comment]
Thanks! Published in v4.1.13

**Comment by yash-toddleapp** [comment]
why was 139.com added back to the list?

**Comment by Yuki1536** [comment]
> why was 139.com added back to the list?

I don't know about that. I have an account of 139mail, which is under the administration of China Mobile Corp. I'm sure it's a legitimate email service provider.
image

**Comment by Yuki1536** [comment]
> why was 139.com added back to the list?

I don't know about that. 139mail is under the administration of China Mobile Corp and I'm one of its users. I'm sure it's a legitimate email service provider. (You may have its account if you have a CM/CMI phone number.)
image

**Pull request merged**
