### PR TITLE
Consider all domain suffixes for blacklisting and normalise implementations

### PR DESCRIPTION
**Pull request by owst**
This change was triggered by the Ruby implementation not matching any blacklisted domains with more than 1 subdomain, e.g. `test@spamthis.co.uk` would not be considered invalid, even though `spamthis.co.uk` is a blacklisted domain.

This refactoring normalises the implementation across the 7 languages:

1. We're now using the same regexp for email wellformed-checking,
2. All suffixes of an email's domain are checked for blacklist membership in the same way (modulo language/library differences),
3. The test cases are now the same for each implementation.

This removes false-negatives (e.g. where the domain includes > 2 subdomains) in some cases, and false-positives (e.g. where a blacklisted domain appears as a subdomain) in other cases.

As a side effect, several improvements were made to the tests of PHP, Python in particular, using standard libraries for unit testing rather than ad-hoc tests.

Meta: I think this will be easiest to review on a commit-by-commit basis. This PR is based off my other pending PR, so that PR's commit also shows up here.

### CODE REVIEW

**Comment by owst** [comment]
I can't work out why circle ci is failing on `composer install` I was able to run that locally with no problem. Perhaps a version issue, I'm on: 
```
~ composer --version
Composer version 1.0.0-alpha11 2015-11-14 16:21:07
```

**Comment by FGRibreau** [comment]
Very impressive work @owst!! Thanks a lot!

**Comment by owst** [comment]
You're welcome, thanks for maintaining the project! 

How do we go about getting a new Ruby gem published? At work we're currently overriding `MailChecker.valid_email?`, so it'd be good to get rid of that code by using a newly published version.

By the way, do you have any idea why `composer` failed on Circle CI?

**Comment by FGRibreau** [comment]
Hello @owst ,

It's now fixed, I pushed ruby-mailchecker-1.6.3.gem :)

**Comment by owst** [comment]
Great, thanks!

**Pull request merged**
