### PR TITLE
PHP class: convert isBlacklisted method in public

### PR DESCRIPTION
**Pull request by apachejack**
Hi again, 

Sorry, I think I edited the incorrect file in my last PR. Looks more logical editing the template file (.tmpl.php) instead of the compiled one with the blacklisted emails. 
I downloaded the latest version of the library and I didn't see my changes in the class.

Thanks again. 

I copy again the reasons for changing this code: 

> 
> I would like to convert one of the methods in public to be able to use the black-list without validating the email using the PHP filter function.
> 
> filter_var($email, FILTER_VALIDATE_EMAIL) doesn't validate correctly the allowed email patterns exposed in this Wikipedia article: https://en.wikipedia.org/wiki/Email_address#Local-part
> 
> Thanks for this great job,
> Kind regards.

### CODE REVIEW

**Comment by FGRibreau** [comment]
@apachejack could you please rebase?

**Comment by FGRibreau** [comment]
Released in v3.1.0

**Comment by apachejack** [comment]
Hi @FGRibreau  

Why is this change not reflected in the file MailChecker.php despite the template file was modified https://github.com/FGRibreau/mailchecker/blob/master/platform/php/MailChecker.php?

Am I doing something wrong? :( 

Thanks again, 
Kind regards.

**Comment by FGRibreau** [comment]
There was an issue on the release script, it's fixed thus available in v3.2.0

**Pull request closed without merging**
