### PR TITLE
More domains for blacklist and better order

### PR DESCRIPTION
**Pull request by quaswex**

### CODE REVIEW

**Comment by FGRibreau** [comment]
@quaswex could you please rebase (I will merge it then)

**Comment by quaswex** [comment]
Rebase

**Comment by quaswex** [comment]
Sorry, I'm not quite sure how to rebase it in Github UI. Seems I don't have enough rights – can't see anything [similar](https://help.github.com/articles/merging-a-pull-request/) to rebasing manual.

**Comment by FGRibreau** [comment]
@quaswex if you don't know how to rebase, just close this PR, fork again the repo, edit list.json, commit and submit again a PR :)

**Pull request closed without merging**
