### PR TITLE
We should not blacklist all email addresses with the TLD pp.ua

### PR DESCRIPTION
**Pull request by L3o-pold**

### CODE REVIEW

**Comment by FGRibreau** [comment]
And why is that?

**Comment by L3o-pold** [comment]
Why what? The pp.ua extension is for Ukrain domain. You really want to blacklist all this TLD?

**Comment by FGRibreau** [comment]
@L3o-pold indeed! Could you please rebase and only change the .gitignore, README.md, list.json and test/platform.node.test.js ? thanks, I will merge it once its done

**Comment by L3o-pold** [comment]
@FGRibreau Not sure if I did this correctly...

**Comment by FGRibreau** [comment]
Released in v3.2.15 :)

**Pull request closed without merging**
