### PR TITLE
clipmails.com, temp-mail.org and many more

### PR DESCRIPTION
**Pull request by nalgeon**
Recently I faced a lot of 'disposable' signups and discovered that all of their domains are covered in https://github.com/andreis/disposable-email-domains. So I added them to list.txt

### CODE REVIEW

**Comment by nalgeon** [comment]
@FGRibreau?

**Comment by FGRibreau** [comment]
Hello!

Thanks a lot for your PR, however I see that some domains have been removed but not added again, for instance:  SpamHerePlease.com and SpamHereLots.com.

Please update your PR and be sure already present domains are not lost :)

**Comment by nalgeon** [comment]
They are all there, but lowercased for consistence. See for yourself:
```
$ grep -i SpamHerePlease.com list.txt 
spamhereplease.com

$ grep -i SpamHereLots.com list.txt 
spamherelots.com
```

**Comment by FGRibreau** [comment]
My bad, I also tested it with `grep -i` but it might have been on the wrong file (current mailchecker list.txt) 🤦‍♂ ...

Released in v3.2.30, thanks :+1:

**Pull request merged**
